"""add maps

Revision ID: 126508880fb2
Revises: 
Create Date: 2020-12-20 03:14:49.886190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126508880fb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_records', sa.Column('map10', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map11', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map12', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map13', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map14', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map15', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map16', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map17', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map18', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map19', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map20', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map21', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map22', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map23', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map24', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map25', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map26', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map27', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map28', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map29', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map30', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map31', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map32', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map33', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map34', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map35', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map36', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map37', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map38', sa.Float(), nullable=True))
    op.add_column('map_records', sa.Column('map9', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_records', 'map9')
    op.drop_column('map_records', 'map38')
    op.drop_column('map_records', 'map37')
    op.drop_column('map_records', 'map36')
    op.drop_column('map_records', 'map35')
    op.drop_column('map_records', 'map34')
    op.drop_column('map_records', 'map33')
    op.drop_column('map_records', 'map32')
    op.drop_column('map_records', 'map31')
    op.drop_column('map_records', 'map30')
    op.drop_column('map_records', 'map29')
    op.drop_column('map_records', 'map28')
    op.drop_column('map_records', 'map27')
    op.drop_column('map_records', 'map26')
    op.drop_column('map_records', 'map25')
    op.drop_column('map_records', 'map24')
    op.drop_column('map_records', 'map23')
    op.drop_column('map_records', 'map22')
    op.drop_column('map_records', 'map21')
    op.drop_column('map_records', 'map20')
    op.drop_column('map_records', 'map19')
    op.drop_column('map_records', 'map18')
    op.drop_column('map_records', 'map17')
    op.drop_column('map_records', 'map16')
    op.drop_column('map_records', 'map15')
    op.drop_column('map_records', 'map14')
    op.drop_column('map_records', 'map13')
    op.drop_column('map_records', 'map12')
    op.drop_column('map_records', 'map11')
    op.drop_column('map_records', 'map10')
    # ### end Alembic commands ###
