"""visitor_count

Revision ID: 5c4197c7f575
Revises: c027c8b929fc
Create Date: 2021-01-01 03:02:39.806997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4197c7f575'
down_revision = 'c027c8b929fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('visitor_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'visitor_count')
    # ### end Alembic commands ###
